name: ui_kit
description: "A new Flutter package project."
resolution: workspace
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.10.1
  flutter_lints: ^5.0.0



flutter:
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf

      