name: client_app
description: "A new Flutter project."
resolution: workspace
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  ui_kit:
    path: ../../packages/ui_kit

  core:
    path: ../../packages/core

  

  cupertino_icons: ^1.0.8
  auto_route: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1


flutter:
  uses-material-design: true
